version: '3'
services:
  redis:
    container_name: redis-carrinhos
    hostname: redis
    image: redis:alpine
    ports:
      - "5002:6372"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"